//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CitasWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cita
    {
        public int idCita { get; set; }
        public string idPaciente { get; set; }
        public string idDoctor { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> idTipoCita { get; set; }
        public Nullable<int> aviso { get; set; }
        public Nullable<int> idSala { get; set; }
        public string estado { get; set; }
    
        public virtual doctore doctore { get; set; }
        public virtual paciente paciente { get; set; }
        public virtual sala sala { get; set; }
        public virtual tipocita tipocita { get; set; }
    }
}
